#!/bin/bash

/usr/bin/php -f /home/worker/event_handlers/run.php AnyEventSwitcher unbind ONCRMCOMPANYUPDATE

/usr/bin/php -f /home/worker/event_handlers/run.php PrevHandlerSwitch bind ONCRMCOMPANYUPDATE
